### ISSUE TITLE
[RSE-Dev] - ssh: Retrieve user group, user default paths on any server

### ISSUE THREAD

**Issue by msarkis-icr** [ICR-RSE-Group/pyalma#28]
### Details

 There was some code that defaulted a users RDS or SCRACTH path based on their group, and we talked about adding it to pyalma with some config.yaml 
This code already exists in Cosmx app and nextflow app. 

Objective:
Write a generic solution to avoid duplicating that code across apps

**Comment by rachelicr** [comment]
I don;t think we need to rush this, I envisage the username being a wildcard as the most likely, so something like customisable tags for the types of path

HOME:
/data/RDS/RSE/%USER% = [ralcraft,msarkis]
/data/RDS/TARTHER/%USER% = [amy]
etc

SCRATCH:
/data/RDS/RSE/%USER%/scratch = [ralcraft,msarkis]
/data/RDS/TARTHER/%USER%/scratch = [amy]
etc

RDS:
etc...

**Comment by msarkis-icr** [comment]
> Can you add what the config should like like in the issue? 
The config file is a yaml file that has the following structure. 
```
group_paths:
  infotech:
    scratch: "/data/scratch/DCO/DIGOPS/SCIENCOM/{username}"
    rds: "/data/rds/DIT/SCICOM/SCRSE"
  default:
    scratch: "/scratch/{username}/{group}"
    rds: "/rds/general/user/{username}/home"
```

`group_paths` is obligatory as well as `default`

> Also, how do you use the config?
the config file (.yaml) is optional and should be passed at construction time, in the constructor

```
    def __init__(self, server="alma.icr.ac.uk", username=None, password=None, sftp="alma-app.icr.ac.uk", custom_yaml=None):

```

To retrieve the user paths, you call `get_user_paths` which requires:
* group : (string)
* locations: a list, for example ["scratch", "rds"]
and returns a dictionary mapping location:path`

**Comment by msarkis-icr** [comment]
> I don;t think we need to rush this, I envisage the username being a wildcard as the most likely, so something like customisable tags for the types of path
> 
> HOME: /data/RDS/RSE/%USER% = [ralcraft,msarkis] /data/RDS/TARTHER/%USER% = [amy] etc
> 
> SCRATCH: /data/RDS/RSE/%USER%/scratch = [ralcraft,msarkis] /data/RDS/TARTHER/%USER%/scratch = [amy] etc
> 
> RDS: etc...
> 
> optionally initialised so they would then be useable but not a requirement.

The idea is mostly to avoid duplicating more codes among the different apps. 
We can do another round to update the yaml files.

**Comment by msarkis-icr** [comment]
Following what you have proposed, we can add user_paths into the yaml. user_paths map each user to a group. 
```
user_paths:
  ralcraft:
    group: RSE
  msarkis:
    group: RSE
  amy:
    group: TARTHER

group_paths:
  RSE:
    scratch: "/data/scratch/RSE/{username}"
    rds: "/data/RDS/RSE/{username}"
  TARTHER:
    scratch: "/data/scratch/TARTHER/{username}"
    rds: "/data/RDS/TARTHER/{username}"

default:
  scratch: "/scratch/{username}/{group}"
  rds: "/rds/general/user/{username}/home"


```

**Comment by rachelicr** [comment]
I haven't proposed anything, was just meant to be a discussion, I am happy with what you have done for now!

**Comment by rachelicr** [comment]
My paths are:
/data/scratch/DCO/DIGOPS/SCIENCOM/ralcraft
/data/rds/DIT/SCICOM/SCRSE

Syed's are (just to show the inconsistency and convention):
/data/scratch/DBC/UBCN/BCRBIOIN/shaider
/data/rds/DBC/UBCN/BCRBIOIN

Most people would have 3 paths consistent as their group to make it easy, eg DBC/UBCN/BCRBIOIN but annoyingly we don't.

So it would seem to be something like (formatted correctly...)

```
groups:
SCRSE: ralcraft,msarkis...
BCRBIOIN: shaider, fgroll...

group_paths:
  SCRSE:
    scratch: "/data/scratch/DCO/DIGOPS/SCIENCOM/{username}"
    rds: "/data/rds/DIT/SCICOM/SCRSE"

  BCRBIOIN: 
    scratch: "/data/scratch/DBC/UBCN/BCRBIOIN/{username}"
    rds: "/data/rds/DBC/UBCN/BCRBIOIN"

  default:
    scratch: "data/scratch/UNKNOWN/{username}"
    rds: "data/rds/UNKNOWN/{username}"

```
If user not in a group then default.
